export const THEME_LOAD_DATA_START = 'THEME_LOAD_DATA_START';

export const THEME_LOAD_DATA_FINISH = 'THEME_LOAD_DATA_FINISH';

export const THEME_LOAD_MORE_START = 'THEME_LOAD_MORE_START';

export const THEME_LOAD_MORE_FINISH = 'THEME_LOAD_MORE_FINISH';