export const INDEX_LOAD_DATA_START = 'INDEX_LOAD_DATA_START';

export const INDEX_LOAD_DATA_FINISH = 'INDEX_LOAD_DATA_FINISH';

export const INDEX_LOAD_MORE_START = 'INDEX_LOAD_MORE_START';

export const INDEX_LOAD_MORE_FINISH = 'INDEX_LOAD_MORE_FINISH';